### PR TITLE
Feat: add graph-populate-hooks

### LINKED ISSUE #24: add so called `hooks` - way of passing stuff from one `context` to another
Please see #23 for more information. This will be super useful for me to pass the requesting user from first request to all populate requests.

### PR DESCRIPTION
**Pull request by fratzinger**
## Caution:
For this PR. The [PR for shallow-populate](https://github.com/Mattchewone/feathers-shallow-populate/pull/20) is necessary.
After merge & publish `feathers-shallow-populate` update the dependency here.

## Problem:
When an external request comes in, I need to keep information about authenticated user, provider, ... Since `feathers-shallow-populate` allows to customize the params I can add these information to every `populate` manually. For my application that are multiple files with multiple `populates` which would be tedious to organize. The best approach for me would be to have one single place where I can define conditional params that gets passed from service to service

## Solution: `graph-populate-hooks`:
Pretty similar to `hooks` of `@feathersjs/feathers` this PR adds hooks for `feathers-graph-populate`. There are app wide hooks and service hooks. Since `feathers-shallow-populate` allows an array of `params`/`function(params, context)` the concept an hooks-array was easy to integrate.

## Setup:
```typescript
//app.ts
import graphPopulate from 'feathers-graph-populate'
import graphPopulateHooks from './graph-populate.app.hooks.ts'

//...

app.configure(graphPopulate())
// sets `app.graphPopulate` and service mixin `app.service(...).graphPopulate`
// can set hooks with `app.graphPopulate.hooks()` and `app.service(...).graphPopulate.hooks()`

app.graphPopulate.hooks(graphPopulateHooks)
```
with
```typescript
// src/graph-populate.app.hooks.ts
export default {
  before: {
    all: [
      (params, context) => {
        if (context.params?.user) {
          params.user = context.params.user
        }
      }
    ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: [],
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: [],
  }
};
```

`before` maybe is misleading. It's after the params from `graph-Populate` (`query: { id: { $in: [...] } }`) but before individual params defined in `populates`. `after` then is after the individual params.

## Things left to do:
- [x] add more tests
- [x] add docs
- [ ] spot if `before` and `after` are necessary
- [x] *for later*: add third parameter for hooks with current service
- [ ] *for later*: integrate `error` hooks

Marshall, what do you think about `before` and `after`? IMO `before` maybe should be the very first `params` before the `$in` query. But that would result in a bigger refactor of `feathers-shallow-populate`.

Closes #24

### CODE REVIEW

**Comment by marshallswain** [comment]
I think the before/after is perfect.  Having the $in arrays in place is important.  You can always modify them.

**Comment by marshallswain** [comment]
I'll merge and release if this is ready. Let me know.

**Comment by marshallswain** [comment]
By the way, great idea adding hooks like this.

**Comment by marshallswain** [comment]
@fratzinger thank you.  This has been released as https://github.com/marshallswain/feathers-graph-populate/releases/tag/v1.3.0.

**Comment by marshallswain** [comment]
The release notes are a bit thinner than I normally do, but I'm on a major time crunch.  Thanks again!

**Comment by fratzinger** [comment]
Thanks for merging and releasing :) Don't worry about the release notes!
Sorry for not answering for a week. I'll give it a go in my production app and see how it goes.

**Pull request merged**
