### PR TITLE
move to Typescript

### PR DESCRIPTION
**Pull request by fratzinger**
This was pretty straight forward. I would like to add more functionality to `feathers-graph-populate`. For this, I think the transition to typescript is a good starting point.

Let me know what you think and how I can help

### CODE REVIEW

**Comment by marshallswain** [comment]
Cool!  Thanks!

**Comment by fratzinger** [comment]
Wow. That was fast. Thanks for merging.
I love it to contribute to your awesome packages!

**Comment by marshallswain** [comment]
I was really happy this morning when I used some of the new features in a data heavy api.  It’s easy to merge great code.  😆

**Comment by fratzinger** [comment]
Nice! I even did not use them myself yet 😆
But I'm currently working on new features for `feathers-graph-populate`. Hopefully I can make another PR within the next days.

**Pull request merged**
